#!/bin/bash
logfile="/dev/null"

if [ "$(cat ~/bin/nm)" = "RDP" ]; then
  echo "Work in Progress......   "
  sudo apt-get -y install policykit-1 >> $logfile 2>&1
  sudo apt-get -y install tightvncserver >> $logfile 2>&1
  sudo dpkg -i /etc/seedbox-from-scratch/xrdp_0.6.1-1_`uname -m`.deb 
  sudo apt-get -f -y install
  echo "........"
  echo "............."
  echo "Work in Progress.........   "
  echo "Please Standby................   "
  sudo apt-get -y install lxde >> $logfile 2>&1
  sudo apt-get -y install firefox
  sleep 1
  sudo ./RDPconfig.sh
fi
