#!/bin/bash
IPADDRESS1=`cat /etc/seedbox-from-scratch/hostname.info`
OS1=$(lsb_release -si)
OSV1=$(lsb_release -rs)
OSV11=$(sed 's/\..*//' /etc/debian_version)
logfile="/dev/null"
#Sickrage
echo "Installing SiCKRAGE . . ."
sudo apt-get -y install python-cheetah python
sudo git clone https://github.com/SickRage/SickRage.git /opt/SickRage
sudo chown $(whoami):$(whoami) -R /opt/SickRage

if [ "$OSV1" = "15.04" ] || [ "$OSV1" = "15.10" ] || [ "$OSV11" = "8" ]; then
  sudo perl -pi -e "s/<username>/$(whoami)/g" /etc/seedbox-from-scratch/sickrageservice
  mv /etc/seedbox-from-scratch/sickrageservice /etc/systemd/system/sickrage.service
  sudo systemctl enable sickrage.service
  sudo service sickrage start
else
  #sudo perl -pi -e "s/<username>/$(whoami)/g" /etc/seedbox-from-scratch/sickrageconf
  #mv /etc/seedbox-from-scratch/sickrageconf /etc/init/sickrage.conf
  #sudo apt-get install upstart	
  sudo wget http://cheapseedboxes.com/sickrage -P /etc/init.d/
  sudo chmod +x /etc/init.d/sickrage
  sudo wget http://cheapseedboxes.com/csickrage -P /etc/default/
  sudo perl -pi -e "s/root/$(whoami)/g" /etc/default/csickrage
  sudo perl -pi -e "s/DATADIR=/DATADIR=\/home\/$(whoami)/g" /etc/default/csickrage
  sudo update-rc.d sickrage defaults
  sudo service sickrage start
fi
echo ""
echo "SiCKRAGE Installed"
echo "Access - http://$IPADDRESS1:8081 and setup username & password"
echo ""
