#!/bin/bash
MAINUSER1=`cat /etc/seedbox-from-scratch/mainuser.info`
IPADDRESS1=`cat /etc/seedbox-from-scratch/hostname.info`
logfile="/dev/null"
echo "Installing Subsonic . . . . "
#Subsonic
sudo apt-get -y install openjdk-7-jre >> $logfile 2>&1
wget http://subsonic.org/download/subsonic-6.0.deb >> $logfile 2>&1
sudo dpkg -i subsonic-6.0.deb >> $logfile 2>&1
sudo chmod -R 755 /etc/default/subsonic
sudo perl -pi -e "s/root/$MAINUSER1/g" /etc/default/subsonic
rm subsonic-6.0.deb
sudo service subsonic restart
echo ""
echo ""
echo "Subsonic is installed."
echo "Access Subsonic on http://$IPADDRESS1:4040 "
echo "Change admin password ASAP "
echo ""
echo "By default, Subsonic has trial license."
echo "To get all features, check this thread:"
echo " http://www.torrent-invites.com/showthread.php?t=232744 "
echo ""
echo ""
