#!/bin/bash
echo "This will remove quotaspace plugin and install Diskspace plugin for Single user"
echo "Remember, this process is not reversible, if you are in doubt, press Ctrl+C"
sudo rm -r /var/www/rutorrent/plugins/quotaspace >> /dev/null 2>&1
wget https://github.com/Novik/ruTorrent/archive/master.zip >> /dev/null 2>&1
unzip master.zip >> /dev/null 2>&1
sudo cp -R ruTorrent-master/plugins/diskspace/ /var/www/rutorrent/plugins/
rm master.zip 
rm -r ruTorrent-master/
echo "It's done, quotasapce plugin removed and Diskspace plugin installed"
