#!/bin/bash 

## This script to run after install to install latest znc
MAINUSER1=`cat /etc/seedbox-from-scratch/mainuser.info`
 
## Crontab to start ZNC on reboot
if [ `logname` = "$MAINUSER1" ]; then
  echo ""
  echo -e "\033[0;32;148mInstalling ZNC...\033[39m"
  echo ""
  cd ~
  if [ "$(crontab -l 2> /dev/null | grep -c znc)" == "0" ]; then
  wget --no-check-certificate https://raw.githubusercontent.com/dannyti/sboxsetup/master/startznc
  perl -pi -e "s/USERNAME/`logname`/g" startznc
  chmod +x startznc
  bash startznc
  fi
  wget http://znc.in/releases/znc-latest.tar.gz
  tar -xzvf znc*.*gz
  cd znc-*
  ./configure --prefix=$HOME/znc
  make
  make install
  rm -r ~/znc-*
  echo
  echo -e "\033[0;32;148mPlease configure ZNC...\033[39m"
  echo
  ~/znc/bin/znc --makeconf
  rm /home/`logname`/startznc
else
  echo -e "\033[0;32;148mPlease install ZNC as Main User.\033[39m"
fi
